language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - cd ..
  - django-admin.py startproject --template=./skeleton --extension=py my_proj
  - cd my_proj
  - python manage.py migrate
script:
  - python manage.py test